### ISSUE TITLE
Predicate comparing Promise object with number

### ISSUE THREAD

**Issue by Xotabu4** [CrispusDH/protractor-typescript-initial#1]
https://github.com/CrispusDH/protractor-typescript-initial/blob/b075024cb961c938c383f0343c094041bea3ba73/src/utils/waiters/predicates.ts#L16

await array.count() - returns promise
await array.count() > 0 - will check promise to be more than 0 which is always true

Rewrite to 
(await array.count()) > 0

**Comment by CrispusDH** [comment]
it works as expected without fix, take a look at this [playground](http://www.typescriptlang.org/play/index.html#src=async%20function%20getNumber()%3A%20Promise%3Cnumber%3E%20%7B%0D%0A%20%20%20%20return%20-2%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20check()%3A%20Promise%3Cboolean%3E%20%7B%0D%0A%20%20%20%20return%20await%20getNumber()%20%3E%200%3B%0D%0A%7D%0D%0A%0D%0Acheck().then((value)%20%3D%3E%20alert(value))%3B)
